# register a user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "pacwozis@majjud.mz",
  "password": "basic1pass!"
}
###

# get session
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "pacwozis@majjud.mz",
  "password": "basic1pass!"
}
###

GET http://localhost:3000/auth/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoicGFjd296aXNAbWFqanVkLm16IiwibmFtZSI6bnVsbCwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEzMjEyMDc0LCJleHAiOjE3MTM0NzEyNzR9.rCTTgbd6fdJOc8-sLqaPWkC1gVYdS9C_Dln_rpUXh3g
