GET http://localhost:3000/products HTTP/1.1
###

# pagination
GET http://localhost:3000/products?limit=2&offset=0 HTTP/1.1
###
 
# find by id
GET http://localhost:3000/products/10 HTTP/1.1
###
 
# find by categoryId
GET http://localhost:3000/products/category?id=1&limit=10&offset=0 HTTP/1.1
###
 
# find by styleId
GET http://localhost:3000/products/style?id=1&limit=10&offset=0 HTTP/1.1
###
 
# find by brandId
GET http://localhost:3000/products/brand?id=1&limit=10&offset=0 HTTP/1.1
###


# create a new country
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicG9yZHVjQGJ1LnZpIiwibmFtZSI6InBvcmR1YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDQzMDMyMywiZXhwIjoxNzE0Njg5NTIzfQ.bA0jeCwsH6770mSL8b10NyFxpXuTi_irJcm5tUyAhew

{
  "categoryId": 1,
  "brandId": 2,
  "styleId": 1,
  "name": "product 1",
  "description": "description",
  "images": ["http://li.it/na", "http://paujic.mx/honip"],
  "characteristics": ["Montura de Acetato", "Sin plaquetas", "Patillas Firmes", "Estilo Moderno" ,"Calibre 54"],
  "prices": {
    "price": 50,
    "discount": 1,
    "currency": "usd"
  }
}
###

# update a product by id
PATCH http://localhost:3000/products/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicG9yZHVjQGJ1LnZpIiwibmFtZSI6InBvcmR1YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMzQ1NDIwMiwiZXhwIjoxNzEzNzEzNDAyfQ.5EswLVu8WSky45m19ExoCB0hffXFlATDzza8K2SVGg0

{
  "prices": {
    "price": 10,
    "currency": "pyg"
  }
}
###

# delete a product by id
DELETE http://localhost:3000/products/10  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicG9yZHVjQGJ1LnZpIiwibmFtZSI6InBvcmR1YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDQ4ODcyOCwiZXhwIjoxNzE0NzQ3OTI4fQ.k0Eka8pz2e2U9-BqleHnlwtrZdvsOf1Wsg-BHznevg4